# Generated by Django 5.2 on 2025-08-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['booked_at']},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_class',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_classes',
            field=models.ManyToManyField(related_name='tickets', to='events.ticketclass'),
        ),
    ]
