# Generated by Django 5.2 on 2025-08-13 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_alter_ticket_options_remove_ticket_ticket_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='ticket_class',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='ticket_classes',
            field=models.ManyToManyField(null=True, related_name='paymentlogs', to='events.ticketclass'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
