# Generated by Django 5.2 on 2025-08-13 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_remove_paymentlog_ticket_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='ticket_classes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='ticket_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ticketclass'),
        ),
    ]
