# Generated by Django 5.2 on 2025-08-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_remove_paymentlog_ticket_classes_remove_ticket_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='ticket_class',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='ticket_classes',
            field=models.ManyToManyField(related_name='paymentlogs', to='events.ticketclass'),
        ),
    ]
